version: "3"

services:
  database:
    image: powertic/percona-docker
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - 3306:3306
    volumes:
      - mautic_db:/var/lib/mysql
    restart: always
    networks:
      - mautic_net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: mautic/mautic:v3
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic3
    restart: always
    networks:
      - mautic_net
    ports:
      - 8880:80

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    networks:
      - mautic_net
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mautic_db:
  mautic_data:

networks:
  mautic_net:
