version: "3"

services:
  database:
    image: powertic/percona-docker
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - mautic_db:/var/lib/mysql
    restart: always
    networks:
      - mautic_net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: dirtsimple/mautic-server
    volumes:
      - mautic_data:/data
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mypassword
      - DB_NAME=mautic3
      - MAUTIC_MAIL_HOST=mailhog
      - MAUTIC_MAIL_PORT=1025
    restart: always
    networks:
      - mautic_net
    ports:
      - 8880:80

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    networks:
      - mautic_net
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mautic_db:
  mautic_data:

networks:
  mautic_net:
